SELECT
    COLUMN_NAME,
    CONSTRAINT_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME
FROM
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE
    TABLE_SCHEMA = 'InvoiceApp' AND
    TABLE_NAME = 'invoices' AND
    CONSTRAINT_NAME <> 'PRIMARY';